import Head from 'next/head'
import Image from 'next/image'
import AboutMe from '../components/AboutMe'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hakeemee Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/6840/6840478.png" />
      </Head>
    
    <NavBar />
    <AboutMe />
    </div>
  )
}
