import Head from 'next/head'
import Image from 'next/image'
import AboutMe from '../components/AboutMe'
import NavBar from '../components/NavBar'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hakeemee Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://scontent.fbkk5-4.fna.fbcdn.net/v/t39.30808-6/239647191_2334866879982267_4891519204736256032_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=09cbfe&_nc_eui2=AeGkfm34q-y399sVVzASmy0hKPZ9JdtswAko9n0l22zACb2dm9wFXRzhkU-0sX4KLlIrqIdurF1lgGQDlNVZkRwl&_nc_ohc=Q8LKzphADlYAX9Yy-F9&_nc_ht=scontent.fbkk5-4.fna&oh=00_AT_38k9KS9_XwI9xnQsfJ312KK72ZcWFsIB5OXo6bLXXJw&oe=625AD97A" />
      </Head>
    
    <NavBar />
    <AboutMe />
    
    </div>
  )
}
